name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

    - name: Run tests inside container
      run: |
        # Run container and execute pytest in it
        docker run --rm -e PYTHONPATH=/app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest pytest tests

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
